/* eslint-disable prettier/prettier */
export default {
   mainView: {
      flex: 1,
      alignItems: 'center',
      marginTop:30,
      backgroundColor:'#fff',
   },
   textinput:{
    paddingLeft: 20,
      height:45,
      width:'80%',
      backgroundColor:'#B6B6B6',
      borderRadius:20,
      elevation:7,
   },
   renderView1:
   {
      backgroundColor:'#fff',
      height:200,
      width:'90%',
      justifyContent:'center',
      borderRadius:20,
      elevation:7,
      marginVertical:15,
      marginHorizontal:'5%',
      flexDirection:'row',
   },
   renderView2:
   {
      flex:2,
      justifyContent:'center',
      alignItems:'center',
      paddingLeft:20,
   },
   renderView3:
   {
      flex:4,
      alignItems:'flex-start',
      marginHorizontal:'5%',
      marginTop:'10%',
   },
   ShareTouch:
   {
      backgroundColor:'#EEEBB2',
      height:50,
      width:'60%',
      alignItems:'center',
      justifyContent:'center',
      elevation:10,
      marginHorizontal:'20%',
      marginTop:20,
      borderRadius:30,
   },
   ShareText:
   {
      color:'#000',
      opacity:0.7,
      fontSize:17,
   },
   imagee:
   {
      height:150,
      width:100,
      borderRadius:20,
   },
   View3Text1:
   {
      color:'#000',
      fontSize:17,
      fontWeight:'500',
      opacity:0.7,
   },
   View3Text2:
   {
      color:'#000',
      marginTop:20,
      fontSize:11,
      fontWeight:'300',
   },
   searchTouch:
   {
      marginTop:'7%',
      height:30,
      width:'50%',
      backgroundColor:'#fff',
      alignItems:'center',
      justifyContent:'center',
      flexDirection:'row',
      elevation:5,
      borderRadius:20,
   },
   searchText:
   {
      color:'#4f4f4f',
      fontSize:13,
      opacity:0.7,
      fontWeight:'300',
   },
   Safe:
   {
      width:'100%',
      marginVertical:30,
      height:'80%',
   },

};
